# Generated by Django 5.2.7 on 2025-11-05 13:48

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='lowercase a–z and 0–9 only; no spaces', max_length=120, unique=True, validators=[django.core.validators.RegexValidator(message='Use only lowercase letters and numbers (no spaces or special characters).', regex='^[a-z0-9]+$')])),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='decimal degrees (−90..90) — 6 d.p.', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='decimal degrees (−180..180) — 6 d.p.', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(django.db.models.functions.text.Lower('name'), name='idx_branch_name_lower'), models.Index(fields=['latitude', 'longitude'], name='idx_branch_lat_lon')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_branch_name_lower')],
            },
        ),
        migrations.CreateModel(
            name='BranchOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=255)),
                ('code_hash', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=1)),
                ('last_sent_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['identifier', 'created_at'], name='offers_bran_identif_fe4c6d_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('used', models.BooleanField(default=False)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'expires_at'], name='offers_logi_email_ccf4e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('free_plate', 'Free Plate')], default='free_plate', max_length=32)),
                ('title', models.CharField(default='Free Plate', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('count_start', models.CharField(choices=[('user_registration', 'User registration date'), ('campaign_start', 'Campaign start date')], default='user_registration', max_length=32)),
                ('backfill', models.BooleanField(default=False)),
                ('nth', models.PositiveIntegerField(default=6)),
                ('repeat', models.BooleanField(default=True)),
                ('visit_unit', models.CharField(choices=[('login', 'Login (once per day)'), ('session', 'New session'), ('pageview', 'Any pageview'), ('qr', 'QR scan at outlet')], default='login', max_length=16)),
                ('dedupe_value', models.PositiveIntegerField(default=1)),
                ('dedupe_unit', models.CharField(choices=[('day', 'day'), ('hour', 'hour'), ('minute', 'minute')], default='day', max_length=16)),
                ('per_user_limit', models.CharField(choices=[('per_multiple', 'Once per eligible multiple'), ('once', 'Once only (lifetime)')], default='per_multiple', max_length=16)),
                ('claim_expiry_hours', models.PositiveIntegerField(default=24)),
                ('total_cap', models.PositiveIntegerField(default=0)),
                ('daily_cap', models.PositiveIntegerField(default=0)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('active_from', models.TimeField(blank=True, null=True)),
                ('active_to', models.TimeField(blank=True, null=True)),
                ('all_branches', models.BooleanField(default=False)),
                ('issuance_mode', models.CharField(choices=[('auto', 'Auto-issue on eligibility'), ('claim', 'Require Claim click')], default='auto', max_length=16)),
                ('redeem_type', models.CharField(choices=[('code', 'Unique code / QR'), ('manual', 'Manual verify (staff PIN)')], default='code', max_length=16)),
                ('redeem_methods', models.CharField(blank=True, default='qr', max_length=64)),
                ('fallback_code_length', models.PositiveSmallIntegerField(default=6)),
                ('segment', models.CharField(choices=[('all', 'All users'), ('new_30', 'New users (≤ 30 days)'), ('custom', 'Custom')], default='all', max_length=16)),
                ('exclude_admin', models.BooleanField(default=True)),
                ('allow_key', models.CharField(blank=True, default='', max_length=16)),
                ('allow_list', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eligible_branches', models.ManyToManyField(blank=True, related_name='offers', to='offers.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoginVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('source', models.CharField(choices=[('login', 'Login')], default='login', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'visit_date'], name='offers_logi_user_id_0b2249_idx')],
                'unique_together': {('user', 'visit_date')},
            },
        ),
        migrations.CreateModel(
            name='UserLocationPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy_m', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='browser', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='offers_user_user_id_393866_idx')],
            },
        ),
    ]
