# Generated by Django 5.2.7 on 2025-11-06 06:30

import offers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_branch_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='public_id',
            field=models.CharField(db_index=True, default=offers.models.make_branch_pid, editable=False, help_text='Stable public identifier for URLs/QR (immutable).', max_length=12, unique=True),
        ),
    ]
