# Generated by Django 5.2.7 on 2025-11-14 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_branch_public_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=200)),
                ('pin_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_pins', to='offers.branch')),
            ],
            options={
                'indexes': [models.Index(fields=['pin_hash'], name='offers_qrpi_pin_has_ea9ddc_idx'), models.Index(fields=['branch', 'expires_at'], name='offers_qrpi_branch__ca02a4_idx')],
            },
        ),
    ]
