# Generated by Django 5.2.7 on 2025-11-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_qrpin'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrpin',
            name='desk',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
