# Generated by Django 5.2.7 on 2025-11-14 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_qrpin_desk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRPin',
        ),
    ]
