# Generated by Django 5.2.7 on 2025-11-14 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_delete_qrpin'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desk', models.CharField(blank=True, default='', help_text='Optional desk/counter label, e.g. A1, Main, Cash-1', max_length=12)),
                ('token', models.CharField(db_index=True, max_length=200, unique=True)),
                ('pin_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_pins', to='offers.branch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
