# Generated by Django 5.2.7 on 2025-11-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_qrpin'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrpin',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
