# Generated by Django 5.2.7 on 2025-11-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_qrpin_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='extra_nths',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
