# Generated by Django 5.2.7 on 2025-11-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_offer_extra_nths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='nth',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Free on every Nth visit (optional).', null=True),
        ),
    ]
