# Generated by Django 5.2.7 on 2025-11-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_alter_offer_nth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='visit_unit',
            field=models.CharField(choices=[('qr_screenshot', 'QR scan + screenshot upload'), ('qr_pin', 'QR scan + PIN at outlet')], default='qr_screenshot', max_length=16),
        ),
    ]
