# Generated by Django 5.2.7 on 2025-11-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0011_alter_offer_visit_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplementaryOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('complementary_offer', 'Complementary Offer')], default='complementary_offer', max_length=32)),
                ('title', models.CharField(default='Complementary Offer', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('count_start', models.CharField(choices=[('user_registration', 'User registration date'), ('campaign_start', 'Campaign start date')], default='user_registration', max_length=32)),
                ('backfill', models.BooleanField(default=False)),
                ('nth', models.PositiveIntegerField(blank=True, default=None, help_text='Free on every Nth visit (optional).', null=True)),
                ('repeat', models.BooleanField(default=True)),
                ('extra_nths', models.JSONField(blank=True, default=list)),
                ('visit_unit', models.CharField(choices=[('qr_screenshot', 'QR scan + screenshot upload'), ('qr_pin', 'QR scan + PIN at outlet')], default='qr_screenshot', max_length=16)),
                ('dedupe_value', models.PositiveIntegerField(default=1)),
                ('dedupe_unit', models.CharField(choices=[('day', 'day'), ('hour', 'hour'), ('minute', 'minute')], default='day', max_length=16)),
                ('per_user_limit', models.CharField(choices=[('per_multiple', 'Once per eligible multiple'), ('once', 'Once only (lifetime)')], default='per_multiple', max_length=16)),
                ('claim_expiry_hours', models.PositiveIntegerField(default=24)),
                ('total_cap', models.PositiveIntegerField(default=0)),
                ('daily_cap', models.PositiveIntegerField(default=0)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('active_from', models.TimeField(blank=True, null=True)),
                ('active_to', models.TimeField(blank=True, null=True)),
                ('all_branches', models.BooleanField(default=False)),
                ('issuance_mode', models.CharField(choices=[('auto', 'Auto-issue on eligibility'), ('claim', 'Require Claim click')], default='auto', max_length=16)),
                ('redeem_type', models.CharField(choices=[('code', 'Unique code / QR'), ('manual', 'Manual verify (staff PIN)')], default='code', max_length=16)),
                ('redeem_methods', models.CharField(blank=True, default='qr', max_length=64)),
                ('fallback_code_length', models.PositiveSmallIntegerField(default=6)),
                ('segment', models.CharField(choices=[('all', 'All users'), ('new_30', 'New users (≤ 30 days)'), ('custom', 'Custom')], default='all', max_length=16)),
                ('exclude_admin', models.BooleanField(default=True)),
                ('allow_key', models.CharField(blank=True, default='', max_length=16)),
                ('allow_list', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eligible_branches', models.ManyToManyField(blank=True, related_name='offers', to='offers.branch')),
            ],
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
