# Generated by Django 5.2.7 on 2025-11-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0014_branch_qr_visit_count_qrlandingevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginvisit',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loginvisit',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
    ]
