# Generated by Django 5.2.7 on 2025-11-28 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0015_loginvisit_ip_address_loginvisit_user_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginvisit',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='loginvisit',
            name='user_agent',
        ),
    ]
