# Generated by Django 5.2.7 on 2025-11-28 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0017_loginvisit_ip_address_loginvisit_user_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrlandingevent',
            name='ip_address',
        ),
    ]
