# Generated by Django 5.2.7 on 2025-12-02 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0019_uservisitevent_delete_qrlandingevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='offers.branch')),
            ],
            options={
                'unique_together': {('branch', 'email')},
            },
        ),
    ]
