# Generated by Django 5.2.7 on 2025-12-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0020_branchstaff'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branchstaff',
            unique_together={('branch', 'email')},
        ),
        migrations.AddField(
            model_name='branchstaff',
            name='staff_id',
            field=models.CharField(blank=True, help_text='Unique staff code created by branch', max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='branchstaff',
            unique_together={('branch', 'email'), ('branch', 'staff_id')},
        ),
    ]
