# Generated by Django 5.2.7 on 2025-12-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0021_alter_branchstaff_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservisitevent',
            name='staff_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='uservisitevent',
            name='staff_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
