# Generated by Django 5.2.7 on 2025-12-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0022_uservisitevent_staff_code_uservisitevent_staff_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrpin',
            name='staff_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='qrpin',
            name='staff_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
