# Generated by Django 5.2.7 on 2025-12-09 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0024_visitconfirmpin'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchGenerateVisitPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desk', models.CharField(blank=True, default='', max_length=50)),
                ('token', models.CharField(blank=True, default='', max_length=255)),
                ('pin_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_visit_pins', to='offers.branch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='VisitConfirmPIN',
        ),
    ]
