# Generated by Django 5.2.7 on 2025-12-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0025_branchgeneratevisitpin_delete_visitconfirmpin'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchgeneratevisitpin',
            name='staff_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='branchgeneratevisitpin',
            name='staff_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
