# Generated by Django 5.2.7 on 2025-12-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0026_branchgeneratevisitpin_staff_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchgeneratevisitpin',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
