# Generated by Django 5.2.7 on 2025-12-13 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0028_userverifyvisitpin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRTokenUsage',
        ),
    ]
