# Generated by Django 5.2.7 on 2025-12-13 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0029_delete_qrtokenusage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desk', models.CharField(blank=True, default='', max_length=12)),
                ('token', models.CharField(db_index=True, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used', models.BooleanField(db_index=True, default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('used_via', models.CharField(blank=True, choices=[('', 'Unknown'), ('scan', 'QR Scan'), ('pin', 'PIN Verify')], db_index=True, default='', max_length=16)),
                ('staff_name', models.CharField(blank=True, default='', max_length=255)),
                ('staff_code', models.CharField(blank=True, default='', max_length=100)),
                ('last_error', models.CharField(blank=True, default='', max_length=120)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_tokens', to='offers.branch')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_qr_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='YashPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desk', models.CharField(blank=True, default='', max_length=12)),
                ('pin_hash', models.CharField(db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used', models.BooleanField(db_index=True, default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('staff_name', models.CharField(blank=True, default='', max_length=255)),
                ('staff_code', models.CharField(blank=True, default='', max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yash_pins', to='offers.branch')),
                ('qr_token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yash_pin', to='offers.qrtoken')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_yash_pins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='qrtoken',
            index=models.Index(fields=['branch', 'created_at'], name='offers_qrto_branch__d4bc69_idx'),
        ),
        migrations.AddIndex(
            model_name='qrtoken',
            index=models.Index(fields=['branch', 'expires_at', 'used'], name='offers_qrto_branch__2d6329_idx'),
        ),
        migrations.AddIndex(
            model_name='qrtoken',
            index=models.Index(fields=['token', 'expires_at'], name='offers_qrto_token_3e9d8b_idx'),
        ),
        migrations.AddIndex(
            model_name='yashpin',
            index=models.Index(fields=['branch', 'created_at'], name='offers_yash_branch__e88e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='yashpin',
            index=models.Index(fields=['expires_at', 'used'], name='offers_yash_expires_67de0c_idx'),
        ),
        migrations.AddIndex(
            model_name='yashpin',
            index=models.Index(fields=['pin_hash', 'expires_at'], name='offers_yash_pin_has_139e1d_idx'),
        ),
    ]
