# Generated by Django 5.2.7 on 2025-12-13 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0030_qrtoken_yashpin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qrpin',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrpin',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_qr_pins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qrpin',
            name='used_via',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('scan', 'QR Scan'), ('pin', 'PIN Verify')], db_index=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='qrpin',
            name='desk',
            field=models.CharField(blank=True, default='', help_text='Desk / Counter label (A1, CASH, MAIN)', max_length=12),
        ),
        migrations.AlterField(
            model_name='qrpin',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='qrpin',
            name='pin_hash',
            field=models.CharField(help_text='Hashed 4-digit PIN (never store plain PIN)', max_length=128),
        ),
        migrations.AlterField(
            model_name='qrpin',
            name='used',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='qrpin',
            index=models.Index(fields=['branch', 'created_at'], name='offers_qrpi_branch__fabd8e_idx'),
        ),
        migrations.AddIndex(
            model_name='qrpin',
            index=models.Index(fields=['expires_at', 'used'], name='offers_qrpi_expires_e68668_idx'),
        ),
        migrations.AddIndex(
            model_name='qrpin',
            index=models.Index(fields=['token', 'expires_at'], name='offers_qrpi_token_7b8645_idx'),
        ),
    ]
