# Generated by Django 5.2.7 on 2025-12-14 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0031_qrpin_last_attempt_at_qrpin_used_by_qrpin_used_via_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRPin',
        ),
    ]
