# Generated by Django 5.2.7 on 2025-12-14 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0032_delete_qrpin'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='PAYTM', max_length=20)),
                ('txn_id', models.CharField(max_length=100)),
                ('ref_no', models.CharField(blank=True, default='', max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], max_length=20)),
                ('txn_time', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='offers.branch')),
            ],
            options={
                'indexes': [models.Index(fields=['branch', 'txn_id'], name='offers_rest_branch__327cab_idx'), models.Index(fields=['branch', 'status'], name='offers_rest_branch__9e8656_idx')],
                'unique_together': {('branch', 'txn_id')},
            },
        ),
    ]
