# Generated by Django 5.2.7 on 2025-12-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0033_restauranttransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complementaryoffer',
            name='visit_unit',
            field=models.CharField(choices=[('qr_screenshot', 'QR scan + screenshot upload'), ('qr_pin', 'QR scan + PIN at outlet'), ('qr_scan_location', 'QR scan + auto location verify')], default='qr_pin', help_text='How a user visit is verified and counted.', max_length=32),
        ),
    ]
