# Generated by Django 5.2.7 on 2025-12-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0034_alter_complementaryoffer_visit_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complementaryoffer',
            name='visit_unit',
            field=models.CharField(choices=[('qr_screenshot', 'QR scan + screenshot upload'), ('qr_pin', 'QR scan + PIN at outlet')], default='qr_screenshot', max_length=16),
        ),
    ]
