# Generated by Django 5.2.7 on 2025-12-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0035_alter_complementaryoffer_visit_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchgeneratevisitpin',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branchgeneratevisitpin',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complementaryoffer',
            name='visit_unit',
            field=models.CharField(choices=[('qr_screenshot', 'QR scan + screenshot upload'), ('qr_pin', 'QR scan + PIN at outlet'), ('qr_payment_proof', 'QR scan + payment proof (bill amount / screenshot)')], default='qr_screenshot', max_length=16),
        ),
    ]
