# Generated by Django 5.2.7 on 2025-12-20 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0036_branchgeneratevisitpin_expired_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantTransaction',
        ),
    ]
