# Generated by Django 5.2.7 on 2026-02-10 09:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0037_delete_restauranttransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOfferClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_kind', models.CharField(choices=[('main', 'Main milestone'), ('extra', 'Extra milestone')], max_length=8)),
                ('milestone_n', models.PositiveIntegerField()),
                ('offer_nth', models.PositiveIntegerField(blank=True, null=True)),
                ('offer_repeat', models.BooleanField(default=True)),
                ('offer_extra_nths', models.JSONField(blank=True, default=list)),
                ('offer_start_at', models.DateTimeField(blank=True, null=True)),
                ('offer_end_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('redeemed', 'Redeemed'), ('cancelled', 'Cancelled')], default='issued', max_length=12)),
                ('issued_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('token', models.CharField(blank=True, default='', max_length=255)),
                ('desk', models.CharField(blank=True, default='', max_length=50)),
                ('staff_name', models.CharField(blank=True, default='', max_length=255)),
                ('staff_code', models.CharField(blank=True, default='', max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_claims', to='offers.branch')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='offers.complementaryoffer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_claims', to=settings.AUTH_USER_MODEL)),
                ('visit_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_claims', to='offers.uservisitevent')),
            ],
            options={
                'ordering': ['-issued_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'branch', 'offer', 'milestone_kind', 'milestone_n'), name='uniq_user_branch_offer_milestone'), models.UniqueConstraint(fields=('visit_event', 'milestone_kind', 'milestone_n'), name='uniq_visit_milestone_once')],
            },
        ),
    ]
