# Generated by Django 5.2.7 on 2026-02-16 12:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0039_offerdaypin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='offerdaypin',
            name='offers_offe_created_68afad_idx',
        ),
        migrations.AddField(
            model_name='offerdaypin',
            name='used_by_staff_code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='offerdaypin',
            name='used_by_staff_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerdaypin',
            name='used_by_staff_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='offerdaypin',
            name='pin_hash',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='offerdaypin',
            name='token',
            field=models.CharField(max_length=128),
        ),
        migrations.AddIndex(
            model_name='offerdaypin',
            index=models.Index(fields=['branch', 'used', 'expires_at'], name='offers_offe_branch__6675bf_idx'),
        ),
    ]
