# Generated by Django 5.2.7 on 2026-02-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0040_remove_offerdaypin_offers_offe_created_68afad_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservisitevent',
            name='visit_method',
            field=models.CharField(choices=[('qr_screenshot', 'QR Screenshot Scan'), ('qr_pin', 'QR PIN Entry'), ('offer_day_pin', 'Offer Day PIN')], max_length=20),
        ),
    ]
