# Generated by Django 5.2.7 on 2026-02-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0041_alter_uservisitevent_visit_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complementaryoffer',
            name='visit_unit',
            field=models.CharField(choices=[('qr_code', 'QR code'), ('qr_pin', 'QR scan + PIN at outlet')], default='qr_screenshot', max_length=16),
        ),
    ]
