# Generated by Django 5.2.7 on 2026-03-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0042_alter_complementaryoffer_visit_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complementaryoffer',
            name='visit_unit',
            field=models.CharField(choices=[('qr_code', 'QR code'), ('qr_pin', 'QR scan + PIN at outlet')], default='qr_pin', max_length=16),
        ),
    ]
